# Generated by Django 5.2 on 2025-05-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
