# Generated by Django 5.2 on 2025-05-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='geo_lang',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='geo_lat',
            new_name='lng',
        ),
    ]
