version: '3.12'

services:
  web:
    build: .
    command: >
      /bin/bash -c "
      sleep 10 &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      -  .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    env_file:
      - ./.env

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

volumes:
  postgres_data:
