# Generated by Django 5.2 on 2025-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.URLField(null=True),
        ),
    ]
