# Generated by Django 5.2 on 2025-05-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
